//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPCliente.ServicioWebSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWebSoap.WSOServerSoap")]
    public interface WSOServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumatoria", ReplyAction="*")]
        int sumatoria(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sumatoria", ReplyAction="*")]
        System.Threading.Tasks.Task<int> sumatoriaAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/factorial", ReplyAction="*")]
        int factorial(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<int> factorialAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fibonacci", ReplyAction="*")]
        int fibonacci(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fibonacci", ReplyAction="*")]
        System.Threading.Tasks.Task<int> fibonacciAsync(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOServerSoapChannel : SOAPCliente.ServicioWebSoap.WSOServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOServerSoapClient : System.ServiceModel.ClientBase<SOAPCliente.ServicioWebSoap.WSOServerSoap>, SOAPCliente.ServicioWebSoap.WSOServerSoap {
        
        public WSOServerSoapClient() {
        }
        
        public WSOServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int sumatoria(int num) {
            return base.Channel.sumatoria(num);
        }
        
        public System.Threading.Tasks.Task<int> sumatoriaAsync(int num) {
            return base.Channel.sumatoriaAsync(num);
        }
        
        public int factorial(int num) {
            return base.Channel.factorial(num);
        }
        
        public System.Threading.Tasks.Task<int> factorialAsync(int num) {
            return base.Channel.factorialAsync(num);
        }
        
        public int fibonacci(int num) {
            return base.Channel.fibonacci(num);
        }
        
        public System.Threading.Tasks.Task<int> fibonacciAsync(int num) {
            return base.Channel.fibonacciAsync(num);
        }
    }
}
